### ISSUE TITLE
createFromXML gives back map with just 1 key

### ISSUE THREAD

**Issue by rvypandey** [wso2-extensions/siddhi-execution-map#45]
**Description:**
createFromXML gives back map with just 1 key. Similar question/answer posted - https://stackoverflow.com/a/49407335/1499476

**Suggested Labels:**
Bug

**Suggested Assignees:**
@minudika, @AnuGayan 

**Affected Product Version:**
SP 4.3.0

**OS, DB, other environment details and versions:**    
OS - Windows 10

**Steps to reproduce:**
1. Send an XML to an http sink. The XML should contain an array of children. For example:
```
<body>
  <parent>
    <child1></child1>
    <child2></child2>
    <child3></child3>
    ...
  </parent>
</body>
```
2. Parse the XML using XPath login (like //*[local-name() = "parent"]).
3. This gives back an XML string - `<parent><child1></child1><child2></child2><child3></child3>...</parent>`
4. Now if createFromXML is used to parse this XML to generate a Map, **the output is a map with just one key-pair** (child element).

**Related Issues:**
NA

**Comment by rvypandey** [comment]
Tagging @shubham-kumar14

**Comment by mohanvive** [comment]
The explanation given in the SO is not valid. There is no any override happens here... Please check the test cases give in [1]. Above case works fine without any issue. Please add a test case and reopen the issue if you can reproduce this.

[1] https://github.com/siddhi-io/siddhi-execution-map/blob/master/component/src/test/java/io/siddhi/extension/execution/map/CreateFromXMLFunctionExtensionTestCase.java
